//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string UserFName { get; set; }
        public string UserMName { get; set; }
        public string UserLName { get; set; }
        public string UserMobNo { get; set; }
        public string UserEmailId { get; set; }
        public string UserAltNo { get; set; }
        public string UserPanNo { get; set; }
        public string UserAdhNo { get; set; }
        public int SourceChannelId { get; set; }
    }
}
